services:
  prometheus:
    build:
      dockerfile: ./docker/prometheus.Dockerfile
      context: .
    volumes:
      - ./config/prometheus.yaml:/opt/bitnami/prometheus/prometheus.yml
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    ports:
      - "9002:9090"
    command:
      - '--log.level=debug'

  json_exporter:
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./config/json_exporter.yaml:/config/config.yml
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    command:
      - '--config.file=/config/config.yml'

  my_uplink_exporter:
    image: webdevops/myuplink-exporter:latest
    ports:
      - "9003:8080"
    environment:
      - MYUPLINK_AUTH_CLIENTID=${MYUPLINK_AUTH_CLIENTID}
      - MYUPLINK_AUTH_CLIENTSECRET=${MYUPLINK_AUTH_CLIENTSECRET}