services:
  prometheus:
    image: bitnami/prometheus:latest
    volumes:
      - ./config/prometheus.yaml:/opt/bitnami/prometheus/prometheus.yml
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    command:
      - '--log.level=debug'

  json_exporter:
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./config/json_exporter.yaml:/config/config.yml
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    command:
      - '--config.file=/config/config.yml'
