services:
  prometheus:
    build:
      dockerfile: ./docker/prometheus.Dockerfile
      context: .
    volumes:
      - ./config/prometheus.yaml:/opt/bitnami/prometheus/prometheus.yml
    ports:
      - "9002:9090"
    command:
      - '--log.level=debug'

  json_exporter:
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./config/json_exporter.yaml:/config/config.yml
    command:
      - '--config.file=/config/config.yml'
