services:
  prometheus:
    build:
      dockerfile: ./docker/prometheus.Dockerfile
      context: .
    volumes:
      - ./config/prometheus.yaml:/opt/bitnami/prometheus/prometheus.yml
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    ports:
      - "9002:9090"
    command:
      - '--log.level=debug'

  json_exporter:
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./config/json_exporter.yaml:/config/config.yml
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    command:
      - '--config.file=/config/config.yml'

  nibe_gateway:
    build: https://github.com/garo/nibe-gateway.git
    ports:
      - "9003:3000"
      - "9999:9999/udp"
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ./config/variableinfo.json:/app/variableinfo.json
    environment:
      GATEWAY_ADDRESS: nibegw.local

