{
 "title": "Electricity",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "electricity_price_t1", "query": "0.34461" },
   { "name": "electricity_price_t2", "query": "0.39338" },
   { "name": "fixed_electricity_costs_day", "query": "1.33083" }
  ]
 },
 "panels": [
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_power_w{meter=\"p1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_voltage_l1_v", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_power_import_kwh{meter=\"p1\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Costs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_power_import_t1_kwh{meter=\"p1\"}[$__range]) * $electricity_price_t1",
     "legendFormat": "T1"
    },
    {
     "expr": "increase(total_power_import_t2_kwh{meter=\"p1\"}[$__range]) * $electricity_price_t2",
     "legendFormat": "T2"
    },
    { "expression": "$A + $B + $D", "type": "math" }
   ]
  },
  {
   "title": "Power meters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "active_power_w", "legendFormat": "{{meter}}" }
   ]
  },
  {
   "title": "Power details",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "active_reactive_power_var", "legendFormat": "{{meter}} reactive" },
    { "expr": "active_apparent_power_va", "legendFormat": "{{meter}} apparent" },
    { "expr": "active_power_factor", "legendFormat": "{{meter}} power factor" }
   ]
  },
  {
   "title": "P1 current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "active_current_l1_a", "legendFormat": "Current L1" },
    { "expr": "active_current_l2_a", "legendFormat": "Current L2" },
    { "expr": "active_current_l3_a", "legendFormat": "Current L3" },
    {
     "expr": "active_current_a{meter=\"p1\"}",
     "legendFormat": "Current all"
    }
   ]
  },
  {
   "title": "P1 power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "active_power_l1_w", "legendFormat": "Power L1" },
    { "expr": "active_power_l2_w", "legendFormat": "Power L2" },
    { "expr": "active_power_l3_w", "legendFormat": "Power L3" },
    { "expr": "active_power_w", "legendFormat": "Power all" }
   ]
  },
  {
   "title": "Peak power usage (15m window)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(active_power_w[15m:15m] offset -7m30s)",
     "legendFormat": "{{meter}}"
    }
   ]
  },
  {
   "title": "P1 voltages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "active_voltage_l1_v", "legendFormat": "Voltage L1" },
    { "expr": "active_voltage_l2_v", "legendFormat": "Voltage L2" },
    { "expr": "active_voltage_l3_v", "legendFormat": "Voltage L3" }
   ]
  },
  {
   "title": "Power fails",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "changes(any_power_fail_count[$__interval])",
     "legendFormat": "Any power fail"
    },
    {
     "expr": "changes(long_power_fail_count[$__interval])",
     "legendFormat": "Long power fail"
    }
   ]
  }
 ]
}