{
 "title": "Gas",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "gas_price", "query": "1.44080" },
   { "name": "fixed_gas_price_day", "query": "0.77484" }
  ]
 },
 "panels": [
  {
   "title": "m3/hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    { "expr": "rate(total_gas_m3[1h]) * 3600", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Costs incl. fixed costs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_gas_m3[$__range]) * $gas_price + $fixed_gas_price_day * ($__range_s / 86400)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "m3 total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    { "expr": "total_gas_m3", "legendFormat": "__auto" }
   ]
  }
 ]
}