{
 "title": "Heat pump",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Current status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compressor status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"44457\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressor frequency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"44701\"}",
     "legendFormat": "Compressor frequency"
    }
   ]
  },
  {
   "title": "Indoor temperature (Bt 50)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"40033\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calculated supply temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"43009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Defrosts last 24h",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"50096\"}",
     "legendFormat": "defrost"
    }
   ]
  },
  {
   "title": "Outside temperature (Bt 1)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"40004\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Degree minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"43005\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"44457\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"44457\"}",
     "legendFormat": "status"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "System temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"43009\"}",
     "legendFormat": "Calculated supply"
    },
    {
     "expr": " nibe_register{coilAddress=\"40152\"}",
     "legendFormat": "Return temp (Bt 71)"
    },
    {
     "expr": " nibe_register{coilAddress=\"40071\"}",
     "legendFormat": "Supply temp (Bt 25)"
    }
   ]
  },
  {
   "title": "Air temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"40033\"}",
     "legendFormat": "Indoor temp. (Bt 50)"
    },
    {
     "expr": "nibe_register{coilAddress=\"40004\"}",
     "legendFormat": "Outdoor temp. (Bt 1)"
    }
   ]
  },
  {
   "title": "Heat exchanger temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"44055\"}",
     "legendFormat": "Supply temp (Bt 3)"
    },
    {
     "expr": " nibe_register{coilAddress=\"44058\"}",
     "legendFormat": "Return temp (Bt 12)"
    },
    {
     "expr": " nibe_register{coilAddress=\"44059\"}",
     "legendFormat": "Hot gas (Bt 14)"
    }
   ]
  },
  {
   "title": "Compressor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"40782\"}",
     "legendFormat": "Requested frequency"
    },
    {
     "expr": "nibe_register{coilAddress=\"44701\"}",
     "legendFormat": "Actual frequency"
    }
   ]
  },
  {
   "title": "Evaporator temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"44363\"}",
     "legendFormat": "Evaporator temperature"
    }
   ]
  },
  {
   "title": "Power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "active_power_w{meter=\"kwh_heat_pump\"}",
     "legendFormat": "Active power"
    }
   ]
  },
  {
   "title": "Degree minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "nibe_register{coilAddress=\"43005\"}",
     "legendFormat": "degree minutes"
    },
    { "expression": "$return - $calc", "type": "math" }
   ]
  }
 ]
}