services:
  mimir:
    image: grafana/mimir:latest
    command:
      - "-config.file=/etc/mimir.yaml"
      - "-config.expand-env=true"
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - mimir-data:/data
    ports:
      - "9001:8080"
    environment:
      - AWS_REGION
      - AWS_S3_BUCKET_MIMIR
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID


  grafana:
    image: grafana/grafana:latest
    ports:
      - "9000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/:/etc/grafana/provisioning
      - ./config/grafana.ini:/etc/grafana/grafana.ini

volumes:
  mimir-data:
  grafana-data:
